<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('bibliotecas')->insert([
            ['Id'=> 1, 'Nombre' => 'Marichuela', 'Fecha_Inventario' => '2024-11-28', 'Tabla' => 'bib_1',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 2, 'Nombre' => 'CEFE - CHAPINERO', 'Fecha_Inventario' => '2024-12-18', 'Tabla' => 'bib_2', 'updated_at' => '2024-12-06 16:52:18', 'created_at' => NULL],
            ['Id'=> 3, 'Nombre' => 'Pasquilla', 'Fecha_Inventario' => '2024-12-31', 'Tabla' => 'bib_3', 'updated_at' => '2024-12-06 16:52:14', 'created_at' => NULL],
            ['Id'=> 4, 'Nombre' => 'La Peña', 'Fecha_Inventario' => '2024-11-28', 'Tabla' => 'bib_4',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 5, 'Nombre' => 'La Giralda (SOLO PRÉSTAMO A DOMICILIO)', 'Fecha_Inventario' => '2024-11-28', 'Tabla' => 'bib_5',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 6, 'Nombre' => 'Suba - Francisco José de Caldas', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_6',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 7, 'Nombre' => 'La Victoria', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_7',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 8, 'Nombre' => 'Fontanar - CEFE', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_8',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 9, 'Nombre' => 'Carlos E. Restrepo', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_9',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 10, 'Nombre' => 'Julio Mario Santo Domingo', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_10',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 11, 'Nombre' => 'Bibloestacion Portal Usme', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_11',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 12, 'Nombre' => 'El Tintal Manuel Zapata Olivella', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_12',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 13, 'Nombre' => 'Gabriel García Márquez', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_13',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 14, 'Nombre' => 'Cometas - CEFE', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_14',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 15, 'Nombre' => 'Arborizadora Alta', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_15',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 16, 'Nombre' => 'Fontibón', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_16',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 17, 'Nombre' => 'Las Ferias', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_17',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 18, 'Nombre' => 'Usaquén - Servitá', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_18',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 19, 'Nombre' => 'Bosa', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_19',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 20, 'Nombre' => 'Lago Timiza', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_20',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 21, 'Nombre' => 'Bibloestacion Banderas', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_21',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 22, 'Nombre' => 'Bibloestacion San Diego', 'Fecha_Inventario' => '2024-11-28', 'Tabla' => 'bib_22',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 23, 'Nombre' => 'Bibloestacion Portal 20 de Julio', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_23',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 24, 'Nombre' => 'Virgilio Barco', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_24',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 25, 'Nombre' => 'Perdomo Soledad Lamprea', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_25',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 26, 'Nombre' => 'B_ACM', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_26',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 27, 'Nombre' => 'Sumapaz', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_27',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 28, 'Nombre' => 'Mirador', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_28',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 29, 'Nombre' => 'Bibloestacion Ricaurte', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_29',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 30, 'Nombre' => 'Bibloestacion Portal Sur', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_30',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 31, 'Nombre' => 'Rafael Uribe Uribe', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_31',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 32, 'Nombre' => 'Puente Aranda Nestor Forero Alcalá', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_32',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 33, 'Nombre' => 'Participación Ciudadana', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_33',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 34, 'Nombre' => 'Biblioteca Pública del Deporte y la Actividad Física', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_34',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 35, 'Nombre' => 'Venecia Pablo de Tarso', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_35',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 36, 'Nombre' => 'El Parque', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_36',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 37, 'Nombre' => 'Bibloestacion General Santander', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_37',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 38, 'Nombre' => 'NCENT', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_38',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 39, 'Nombre' => 'Bibloestacion Héroes', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_39',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 40, 'Nombre' => 'Sala de lectura Casa LGTBI Zona Centro', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_40',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 41, 'Nombre' => 'Itinerante', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_41',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 42, 'Nombre' => 'PPP Valles de Cafam', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_42',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 43, 'Nombre' => 'Bibloestacion Tunal - TransMicable', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_43',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 44, 'Nombre' => 'PPP Parque Clarelandia', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_44',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 45, 'Nombre' => 'Especializada en Historia Política - FUGA', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_45',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 46, 'Nombre' => 'PPP Parque Los Novios', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_46',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 47, 'Nombre' => 'Bibloestacion Portal Américas', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_47',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 48, 'Nombre' => 'PPP Parque Naranjos', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_48',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 49, 'Nombre' => 'Sala de lectura Casa LGTBI Teusaquillo', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_49',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 50, 'Nombre' => 'Bibloestacion Portal Suba', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_50',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 51, 'Nombre' => 'Bibloestacion El Dorado', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_51',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 52, 'Nombre' => 'Biblomóvil', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_52',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 53, 'Nombre' => 'Biblioteca Itinerante TIKA', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_53',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 54, 'Nombre' => 'Sala de lectura Manzana del Cuidado Centro', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_54',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 55, 'Nombre' => 'PPP Parque Tronquitos', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_55',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 56, 'Nombre' => 'PPP Ciudad Nuevo Milenio E. I', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_56',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 57, 'Nombre' => 'PPP Urbanización Ciudad Hayuelos', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_57',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 58, 'Nombre' => 'PPP Urbanización San Luis', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_58',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 59, 'Nombre' => 'PPP Corregimiento Betania Raizal', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_59',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 60, 'Nombre' => 'PPP Corregimiento Nazareth', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_60',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 61, 'Nombre' => 'PPP Urbanización Cantalejo', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_61',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 62, 'Nombre' => 'PPP Mirandela', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_62',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 63, 'Nombre' => 'PPP Casablanca', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_63',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 64, 'Nombre' => 'PPP Puente Aranda', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_64',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 65, 'Nombre' => 'PPP Gilma Jiménez', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_65',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 66, 'Nombre' => 'PPP Altos de la estancia', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_66',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 67, 'Nombre' => 'PPP Gustavo Uribe Botero', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_67',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 68, 'Nombre' => 'PPP Urbanización la Esperanza', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_68',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 69, 'Nombre' => 'PPP Jardín Botánico', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_69',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 70, 'Nombre' => 'PPP Parque Santa Ana', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_70',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 71, 'Nombre' => 'PPP Parque Porvenir', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_71',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 72, 'Nombre' => 'PPP Urbanización La Floresta II', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_72',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 73, 'Nombre' => 'PPP Parque La Victoria', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_73',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 74, 'Nombre' => 'PPP Parque Estadio Olaya Herrera', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_74',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 75, 'Nombre' => 'PPP Plazoleta del Rosario', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_75',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 76, 'Nombre' => 'PPP Zona franca', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_76',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 77, 'Nombre' => 'PPP Unidad D. El Salitre', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_77',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 78, 'Nombre' => 'PPP El Taller - El Ensueño', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_78',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 79, 'Nombre' => 'PPP Parque Las Cruces', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_79',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 80, 'Nombre' => 'PPP Parque CDC Lourdes', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_80',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 81, 'Nombre' => 'PPP Parque San Cristóbal', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_81',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 82, 'Nombre' => 'PPP Parque Villa de Los Alpes', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_82',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 83, 'Nombre' => 'PPP Deportivo Primero De Mayo', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_83',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 84, 'Nombre' => 'PPP Parque Molinos II', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_84',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 85, 'Nombre' => 'PPP Parque Pijaos', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_85',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 86, 'Nombre' => 'PPP Parque Bosque de San Carlos', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_86',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 87, 'Nombre' => 'PPP Parque Villa Alemana', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_87',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 88, 'Nombre' => 'PPP La Aurora II', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_88',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 89, 'Nombre' => 'PPP Parque Simón Bolívar', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_89',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 90, 'Nombre' => 'PPP Parque Centro Nariño', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_90',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 91, 'Nombre' => 'PPP Parque Acevedo Tejada', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_91',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 92, 'Nombre' => 'PPP Parque de los Hippies', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_92',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 93, 'Nombre' => 'PPP Conjunto Residencial Atabanza', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_93',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 94, 'Nombre' => 'PPP Parque El Country', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_94',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 95, 'Nombre' => 'PPP Urbanización Altablanca', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_95',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 96, 'Nombre' => 'PPP Parque Nuevo Muzu', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_96',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 97, 'Nombre' => 'PPP Parque El Tunal', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_97',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 98, 'Nombre' => 'PPP Parque El Renacimiento', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_98',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 99, 'Nombre' => 'PPP Parque Eduardo Santos', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_99',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 100, 'Nombre' => 'PPP Parque La Independencia', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_100',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 101, 'Nombre' => 'PPP Parque El Virrey Sur', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_101',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 102, 'Nombre' => 'PPP Parque San Cayetano', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_102',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 103, 'Nombre' => 'PPP Parque La Andrea', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_103',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 104, 'Nombre' => 'PPP Parque Salitre Greco', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_104',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 105, 'Nombre' => 'PPP Parque Paulo VI', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_105',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 106, 'Nombre' => 'PPP Parque Nicolás de Federmán', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_106',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 107, 'Nombre' => 'PPP Parque Sauzalito', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_107',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 108, 'Nombre' => 'PPP Parque Carmen de la Laguna', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_108',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 109, 'Nombre' => 'PPP Parque Atahualpa', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_109',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 110, 'Nombre' => 'PPP Parque Meissen', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_110',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 111, 'Nombre' => 'PPP Parque Illimaní', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_111',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 112, 'Nombre' => 'PPP Parque Candelaria La Nueva', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_112',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 113, 'Nombre' => 'PPP Parque Timiza', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_113',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 114, 'Nombre' => 'PPP Parque Patio Bonito', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_114',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 115, 'Nombre' => 'PPP Parque Cayetano Cañizares', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_115',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 116, 'Nombre' => 'PPP Parque San Andrés', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_116',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 117, 'Nombre' => 'PPP Parque Villa Luz', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_117',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 118, 'Nombre' => 'PPP Parque La Serena', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_118',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 119, 'Nombre' => 'PPP Parque Tibabuyes', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_119',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 120, 'Nombre' => 'PPP Mirador los Nevados', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_120',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 121, 'Nombre' => 'PPP Parque La Gaitana', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_121',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 122, 'Nombre' => 'PPP Parque Fontanar del Río', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_122',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 123, 'Nombre' => 'PPP Parque El Jazmín', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_123',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 124, 'Nombre' => 'PPP Parque Ciudad Montes', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_124',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 125, 'Nombre' => 'PPP Santa Isabel', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_125',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 126, 'Nombre' => 'PPP Parque Gaitán Cortés', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_126',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 127, 'Nombre' => 'PPP Parque Entrenubes', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_127',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 128, 'Nombre' => 'PPP Parque Quiroga', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_128',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 129, 'Nombre' => 'PPP Parque Villa Mayor', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_129',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 130, 'Nombre' => 'PPP Parque La Fragua', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_130',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 131, 'Nombre' => 'PPP Parque Nueva Autopista', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_131',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 132, 'Nombre' => 'PPP Parque Canal El Virrey', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_132',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 133, 'Nombre' => 'PPP Urbanización Carimagua-Parque Lucerna', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_133',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 134, 'Nombre' => 'PPP Parque Castilla', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_134',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 135, 'Nombre' => 'PPP Parque La Amistad', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_135',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 136, 'Nombre' => 'PPP Parque Arborizadora Alta', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_136',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 137, 'Nombre' => 'PPP Parque La Estancia', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_137',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 138, 'Nombre' => 'PPP Autopista Sur', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_138',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 139, 'Nombre' => 'PPP Parque Palestina', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_139',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 140, 'Nombre' => 'PPP Parque Fundacional de Engativá Pueblo', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_140',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 141, 'Nombre' => 'PPP Parque La Florida', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_141',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 142, 'Nombre' => 'PPP Humedal Santa María del Lago', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_142',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 143, 'Nombre' => 'PPP Parque Alcázares', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_143',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 144, 'Nombre' => 'PPP Parque Gimnasio de Norte', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_144',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 145, 'Nombre' => 'PPP Parque El carmelo', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_145',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 146, 'Nombre' => 'Cárcel Distrital', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_146',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 147, 'Nombre' => 'Casa de la Cultura de Usme', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_147',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 148, 'Nombre' => 'Biblioteca 24 horas', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_148',  'updated_at' => NULL, 'created_at' => NULL],
            ['Id'=> 149, 'Nombre' => 'Transitorio', 'Fecha_Inventario' => NULL, 'Tabla' => 'bib_149', 'updated_at' => NULL, 'created_at' => NULL],
        ]);   

        DB::table('menu')->insert([
            ['id' => 1, 'label' => 'Iniciar inventario', 'permiso' => '0', 'activo' => '1', 'orden' => 1.00, 'icono' => NULL],
            ['id' => 2, 'label' => 'Ver avances', 'permiso' => '0', 'activo' => '1', 'orden' => 2.00, 'icono' => NULL],
            ['id' => 3, 'label' => 'Informes', 'permiso' => '0', 'activo' => '0', 'orden' => 3.00, 'icono' => NULL],
            ['id' => 4, 'label' => 'Administración', 'permiso' => '1', 'activo' => '1', 'orden' => 4.00, 'icono' => NULL],
        ]);

        DB::table('usuariosadministradores')->insert([
            ['username' => '1033801141'],
            ['username' => 'cstsojlar'],
            ['username' => 'gticprjpue'],
        ]);

        DB::table('users')->insert([
            [
                "id" => 1,
                "name" => "JOHN DOE",
                "username" => "1033801141",
                "email" => "john.doe@gmail.com",
                "email_verified_at" => null,
                "password" => '$2y$12$8ZdxmLqp.1yU2ftLXaWYC.REsDk8hAXUgqiAxOIFR0jGjUhcHaDDW',
                "remember_token" => null,
                "created_at" => '2024-11-28 05:43:20',
                "updated_at" => '2024-12-16 09:50:10',
                "api_token" => '7642e01d228fef645cc35fb775372845e8569543f009cea476dd4bcfa78d4c95',
            ]
        ]);
    }
}
